### PR TITLE
feat: add async support for csv and dataframe methods

### LINKED ISSUE #54: `AsyncDuneClient` does not have `get_result_csv` method
is there a specific reason for this? is it just a question of it not being written, or is it simply not possible to have an async version of this method?

### PR DESCRIPTION
**Pull request by gosuto-inzasheru**
opening this as a draft to get some feedback.

- add async versions of `get_result_csv`, `_refresh`, `refresh_csv` and `refresh_into_dataframe`
- reduce diff between `client.py` and `client_async.py`, to make future maintenance easier
- `make test-all` passes 100%

closes #54

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by gosuto-inzasheru** [comment]
recheck

**Comment by gosuto-inzasheru** [comment]
im a bit out of depth here.

in the basic client, the `requests`' response is converted to a binary stream using `BytesIO`:
```
return ExecutionResultCSV(data=BytesIO(response.content))
```
however, the `asyncio` variant of our session returns a `StreamReader` type response. although a stream, it cannot be handled by `pandas`' `read_csv`. currently i was able to solve this as such:
```
return ExecutionResultCSV(data=BytesIO(await response.content.read(-1)))
```

but is this really the most efficient way to convert the asynchronous response to something pandas can read?

**Comment by gosuto-inzasheru** [comment]
`client.py` versus `client_async.py`: https://www.diffchecker.com/tXrNtPqY/

**Review by bh2smith — APPROVED** [review]
Hey this looks excellent, really nice job here. I wish there was some way to reduce the overall duplication between the two clients, but I guess not. I have never actually used the async variant and wonder if anyone out there is...

Anyway, this looks great to me!

**Comment by bh2smith** [comment]
Looks good. I will merge and we can tag a new release after a few other of the pending/incoming PRs are landed.

**Comment by gosuto-inzasheru** [comment]
@eliseygusev care to comment on the async aspect here maybe?

**Comment by gosuto-inzasheru** [comment]
i will resolve conflicts and update for updates made to client in #53

**Comment by bh2smith** [comment]
> yes will do, just also have a day job :(

Cool beans. I could also resolve the conflicts here in the interface if its not too wild...

**Comment by gosuto-inzasheru** [comment]
should be good to merge @bh2smith!

- async client now also supports the `performance` param as introduced in #53 
- minimised diff again between `client.py` and `client_aync.py`: https://www.diffchecker.com/ej06mO8H/

**Comment by gosuto-inzasheru** [comment]
@bh2smith what is in the way of merging this? i think waiting will just creates more conflicts down the road for other prs...

**Comment by bh2smith** [comment]
Ya we can merge this... but the performance tier is still failing. Its fine though (aw you explained)

**Review by bh2smith — APPROVED** [review]

**Comment by bh2smith** [comment]
Could you also review #59 --- @gosuto-inzasheru?

**Pull request merged**
